### ISSUE TITLE
Can't start it on Win10 x64

### ISSUE THREAD

**Issue by Egorov-DI** [vitalygashkov/znum#13]
![2024-10-22_14-26-20](https://github.com/user-attachments/assets/ca9529ce-9955-4401-9b79-338555bc85ea)
Can somebody help with it?
Have a lot of books from my study, placed on zNanium, need to download

**Comment by vitalygashkov** [comment]
Try to update Node.js to the latest version (v22).

**Comment by vitalygashkov** [comment]
If issue will persist with latest Node.js LTS version I'll reopen issue. But for now I'm closing it.
